# Generated by Django 4.1.2 on 2022-10-15 23:01

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("aws", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ec2instances",
            name="instance_name",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="ec2instances",
            name="instance_state",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="ec2instances",
            name="instance_tags",
            field=jsonfield.fields.JSONField(default=""),
        ),
    ]
