# Generated by Django 4.1.2 on 2022-10-21 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aws", "0003_alter_ec2instances_instance_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="ec2instances",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 21, 17, 35, 55, 520522)
            ),
        ),
    ]
