# Generated by Django 4.1.2 on 2022-10-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aws", "0004_ec2instances_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ec2instances",
            name="updated_at",
            field=models.DateTimeField(default="10-21-2022 18:06:35"),
        ),
    ]
