# Generated by Django 4.1.2 on 2022-12-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aws", "0006_alter_ec2instances_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ec2instances",
            name="updated_at",
            field=models.DateTimeField(default="12-11-2022 19:34:46"),
        ),
    ]
